version: '3.7'

services:
  shanteacontrols-website:
    container_name: shanteacontrols-website
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - $PWD:/home/ubuntu/website
      - $HOME/.ssh:/home/ubuntu/.ssh
    hostname: localhost
    working_dir: /home/ubuntu/website
    command: tail -f /dev/null