version: '3.7'

services:
  shanteacontrols-website:
    container_name: shanteacontrols-website
    image: paradajz168/website-dev
    volumes:
      - $PWD:/home/ubuntu/website
      - $HOME/.ssh:/home/ubuntu/.ssh
    working_dir: /home/ubuntu/website
    command: tail -f /dev/null