name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04
    container:
      image: paradajz168/website-dev:latest
      options: --user root
    steps:
      - name: Mark repository as safe
        run: git config --global --add safe.directory /__w/website/website
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy
        run: |
          git config --global user.name "web_bot"
          git config --global user.email "2544094+web_bot@users.noreply.github.com"
          export GEM_HOME=/home/shanteacontrols/gems
          export NVM_DIR=/home/shanteacontrols/.nvm
          export PATH="/home/shanteacontrols/gems/bin:$PATH"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          make install
          make prod
          git checkout gh-pages
          cp -R _site/deploy/* .
          git add .
          git commit --allow-empty -m "update"
          git push https://github.com/shanteacontrols/website gh-pages